# yaml-language-server: $schema=https://squidfunk.github.io/mkdocks-material/schema.json
site_name: PyTexas Foundation
repo_url: https://github.com/pytexas/foundation-site
repo_name: GitHub
site_author: Laura Santamaria <dev@nimbinatus.com>
site_description: The PyTexas Foundation is a non-profit dedicated to educating engineers about Python in the state of Texas
copyright: 'PyTexas Foundation © 2023'
theme:
  name: material
  custom_dir: docs/overrides
  locale: en
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png
  features:
    - announce.dismiss
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - toc.follow
    - toc.integrate
  plugins:
    - search
    - social:
        cards_layout: default/variant
  palette:
    - scheme: default
      primary: blue
      accent: amber
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: yellow
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
#docs_dir: docs
#site_dir: site
nav:
  - Home: index.md
  - Foundation:
      - 'About the Foundation': foundation/about.md
      - 'Who we are': foundation/who.md
      - Governance: foundation/governance.md
      - 'Meeting minutes': foundation/minutes.md
      - Fundraising: foundation/fundraising.md
      - Sponsors: foundation/sponsors.md
      - Privacy: privacy.md
  - Conference: conference.md
  - Meetup: meetup.md
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
  
extra:
  status:
    new: Recently added
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/pytexas
    - icon: fontawesome/brands/discord
      link: https://discord.gg/jNPAbcNukj
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/pytexas-foundation
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCkn0L-L6awy9YAmlSy9Kv1Q/playlists
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@pytexas
    - icon: fontawesome/brands/meetup
      link: https://www.meetup.com/pytexas-virtual-meetup
    - icon: fontawesome/brands/github
      link: https://github.com/pytexas