name: Publish

on:
  push:
    branches:
      - build

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install corvid
      run: |
        python -m pip install -U pip setuptools wheel
        python -m pip install --user corvid
    - name: Build content
      run: |
        python -m corvid
    - name: Commit files
      run: |
        cd output
        git init
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -am "[action] Automated deployment"
    - name: Push commit
      env:
        GIT_DEPLOY_KEY: ${{ secrets.GIT_DEPLOY_KEY }}
      run: |
        cd output
        mkdir -p ~/.ssh
        eval "$(ssh-agent -s)"
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        ssh-add - <<< "${GIT_DEPLOY_KEY}"
        git remote -v
        git remote add pytexas git@github.com:pytexas/pytexas.github.io.git
        ssh -Tv git@github.com || true
        git push -f pytexas HEAD:main
